using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Unity.Collections;
using UnityEditor;
using System.Linq;
using System.Diagnostics;
<<<<<<< HEAD
using Unity.Jobs;
using UnityEngine.Jobs;
=======
using System.Threading;
>>>>>>> parent of de138c1... Optimized a bit by turning classes into structs
//Marching cubes terrain script
public class MarchingCubesTerrainScript : MonoBehaviour
{
    public float threshold;//If density value is bigger than this, there is terrain at that 3D point

    /// <summary>
    /// Before making a chunk, we could optimize this terrain by checking if the position of that chunk itself is terrain, if it is then we can generate that chunk
    /// if it is not, we dont have to generate that chunk because we know there is no terrain. But what if the position of the chunk is somewhere where there is not air, but the chunk is actually filled with terrain ? 
    /// Well then we should have another threshold value that controls if those empty (or not) chunks should be generated
    /// We can turn this value low (-1) to make those more empty spaced chunks to generate
    /// Or we can turn it high (0) to make them not generate (Which might cause chunks to not be generated, so it might corrupt the terrain a little) 
    /// </summary>
    public float chunkThreshold;
    public float cubeSize;//The size of the marched cube
    public bool onValidate;//Should we update the terrain if we change one of the parameters in the editor
    public bool interpolation;//Should we use interpolation for the edges points
    public bool mergeVertices;//Merges close vertices to a single vertex
    public float mergeDistance;//distance to merge closest vertices
    public int size;//Size container for each chunk of the marched cube
    public Vector3Int worldSize;//How much chunks we have in the world
    public Material material;
    private MarchingCubesChunk[,,] chunks;
    private Vector3[] marchingPoints;//3D points where the marching cube is going to march through (Only in one single chunk)

<<<<<<< HEAD
    public float scale, offset, yheight;

    public GameObject chunkPrefab;

=======
>>>>>>> parent of de138c1... Optimized a bit by turning classes into structs
    // Start is called before the first frame update
    void Start()
    {
        onValidate = false;
        Destroy(GetComponent<MarchingCubesChunk>());
        Destroy(GetComponent<MeshFilter>());
        Destroy(GetComponent<MeshRenderer>());
        chunks = new MarchingCubesChunk[worldSize.x, worldSize.y, worldSize.z];
        for (int x = 0; x < worldSize.x; x++)
        {
            for (int y = 0; y < worldSize.y; y++)
            {
                for (int z = 0; z < worldSize.z; z++)
                {
                    chunks[x, y, z] = null;
                }
            }
        }
<<<<<<< HEAD
        foreach (var cameras in GameObject.FindObjectsOfType<MarchingCubesCameraScript>())
        {
            cameras.canGenerateChunks = true;
        }

        InitMarchingPoints();
    }
    private void InitMarchingPoints() 
    {
        if(marchingPoints == null || marchingPoints.Length != size) 
        {
            //Set points where the marching cube is going to march through
            marchingPoints = new Vector3[size * size * size];
            for (int x = 0, i = 0; x < size; x++)
            {
                for (int y = 0; y < size; y++)
                {
                    for (int z = 0; z < size; z++, i++)
                    {
                        marchingPoints[i] = new Vector3(x, y, z) * cubeSize;
                    }
                }
            }
        }
=======
>>>>>>> parent of de138c1... Optimized a bit by turning classes into structs
    }

    // Update is called once per frame
    void Update()
    {

    }
    //Marches the cube in a x*x*x grid and generates a mesh out of it
    public Mesh MarchCube(Vector3 position)
    {
<<<<<<< HEAD
        MarchedCubeMeshData meshData;//Variable that will be helpful for storing and moving mesh data
=======
        Stopwatch stopwatch = new Stopwatch();
        stopwatch.Start();
        MeshData meshData;//Variable that will be helpful for storing and moving mesh data
>>>>>>> parent of de138c1... Optimized a bit by turning classes into structs
        meshData.vertices = new List<Vector3>();
        meshData.triangles = new List<int>();
        //Init of the MarchedCube class
        if (marchedCube == null) marchedCube = new MarchedCube(cubeSize, threshold, densityCalculator);
        marchedCube.SetParams(cubeSize, threshold, densityCalculator);

        //Input and output meshes
        Mesh mesh = new Mesh();
        Mesh newmesh = new Mesh();

        List<CombineInstance> meshes = new List<CombineInstance>();
        CombineInstance instance = new CombineInstance();
        instance.transform = transform.localToWorldMatrix;
        int outcase;
<<<<<<< HEAD
        NativeArray<CombineInstance> meshInstances = new NativeArray<CombineInstance>(size * size * size, Allocator.TempJob);
        NativeArray<Vector3> marchingPointsNative = new NativeArray<Vector3>(marchingPoints, Allocator.TempJob);
        NativeArray<MarchedCubeCorner> corners = new NativeArray<MarchedCubeCorner>(8, Allocator.TempJob);
        NativeArray<MarchedCubeEdge> edges = new NativeArray<MarchedCubeEdge>(8, Allocator.TempJob);
        //Init Job
        MarchingCubesMarchJob marchJob = new MarchingCubesMarchJob();
        marchJob.chunkPosition = position;
        marchJob.positions = marchingPointsNative;
        marchJob.interpolation = interpolation;
        marchJob.cubeSize = cubeSize;
        marchJob.threshold = threshold;
        marchJob.outputMeshes = meshInstances;
        marchJob.corners = corners;
        marchJob.edges = edges;
        //Density function parameters
        marchJob.scale = scale;
        marchJob.offset = offset;
        marchJob.yheight = yheight;

        marchJob.Run(size * size * size);

        JobHandle jobHandle = marchJob.Schedule(size * size * size, 64);

        jobHandle.Complete();


=======
        for (int x = 0; x < size; x++)
        {
            for (int z = 0; z < size; z++)
            {
                for (int y = 0; y < size; y++)
                {
                    outcase = marchedCube.MarchCube((new Vector3(x, y, z) * cubeSize) + position);//Get density points at this location
                    meshData = GenerateMesh(outcase, cubeSize, position);//Create a small mesh section out of the density points
                    //Update current mesh
                    newmesh = new Mesh();
                    newmesh.vertices = meshData.vertices.ToArray();
                    newmesh.triangles = meshData.triangles.ToArray();
>>>>>>> parent of de138c1... Optimized a bit by turning classes into structs

        //Create final mesh for this chunk
        meshes = meshInstances.ToList();
        mesh.CombineMeshes(meshes.ToArray(), true);
        if (mergeVertices) AutoWeld(mesh, mergeDistance);
        mesh.Optimize();
        mesh.RecalculateNormals();
        mesh.RecalculateBounds();
<<<<<<< HEAD

        meshInstances.Dispose();
        marchingPointsNative.Dispose();
        corners.Dispose();
        edges.Dispose();

=======
        stopwatch.Stop();
        //UnityEngine.Debug.Log(stopwatch.ElapsedMilliseconds / 1000f);
>>>>>>> parent of de138c1... Optimized a bit by turning classes into structs
        return mesh;
    }
    //Merges vertices that are close to each other https://answers.unity.com/questions/1382854/welding-vertices-at-runtime.html and from https://answers.unity.com/questions/228841/dynamically-combine-verticies-that-share-the-same.html
    public static Mesh WeldVertices(Mesh aMesh, float aMaxDelta = 0.01f)
    {
        var verts = aMesh.vertices;
        Dictionary<Vector3, int> duplicateHashTable = new Dictionary<Vector3, int>();
        List<int> newVerts = new List<int>();
        int[] map = new int[verts.Length];

        //https://answers.unity.com/questions/1382854/welding-vertices-at-runtime.html
        //create mapping and find duplicates, dictionaries are like hashtables, mean fast
        for (int i = 0; i < verts.Length; i++)
        {
            if (!duplicateHashTable.ContainsKey(verts[i]))
            {
                duplicateHashTable.Add(verts[i], newVerts.Count);
                map[i] = newVerts.Count;
                newVerts.Add(i);
            }
            else
            {
                map[i] = duplicateHashTable[verts[i]];
            }
        }

        // create new vertices
        var verts2 = new Vector3[newVerts.Count];
        for (int i = 0; i < newVerts.Count; i++)
        {
            int a = newVerts[i];
            verts2[i] = verts[a];
        }
        // map the triangle to the new vertices
        var tris = aMesh.triangles;
        for (int i = 0; i < tris.Length; i++)
        {
            tris[i] = map[tris[i]];
        }
        aMesh.triangles = tris;
        aMesh.vertices = verts2;

        return aMesh;
    }
    //Merge vertices that are close to each other https://answers.unity.com/questions/228841/dynamically-combine-verticies-that-share-the-same.html
    private void AutoWeld(Mesh mesh, float threshold)
    {
        Vector3[] verts = mesh.vertices;

        // Build new vertex buffer and remove "duplicate" verticies
        // that are within the given threshold.
        List<Vector3> newVerts = new List<Vector3>();

        int k = 0;

        foreach (Vector3 vert in verts)
        {
            // Has vertex already been added to newVerts list?
            foreach (Vector3 newVert in newVerts)
                if (Vector3.Distance(newVert, vert) <= threshold)
                    goto skipToNext;

            // Accept new vertex!
            newVerts.Add(vert);

            skipToNext:;
            ++k;
        }

        // Rebuild triangles using new verticies
        int[] tris = mesh.triangles;
        for (int i = 0; i < tris.Length; ++i)
        {
            // Find new vertex point from buffer
            for (int j = 0; j < newVerts.Count; ++j)
            {
                if (Vector3.Distance(newVerts[j], verts[tris[i]]) <= threshold)
                {
                    tris[i] = j;
                    break;
                }
            }
        }

        // Update mesh!
        mesh.Clear();
        mesh.vertices = newVerts.ToArray();
        mesh.triangles = tris;
    }
<<<<<<< HEAD
    
=======
    //Generate mesh out of the triangulation table and the marchedcube data
    private MeshData GenerateMesh(int outcase, float cubeSize, Vector3 offsetpos)
    {
        List<int> triangles = new List<int>();
        List<Vector3> vertices = new List<Vector3>();
        int currenttriindex;
        for (int i = 0; i < 16; i++)
        {
            currenttriindex = TriangulationTable.triangulation[outcase, i];
            if (currenttriindex != -1)
            {
                triangles.Add(currenttriindex);//Make triangle face
            }
        }
        for (int i = 0; i < 12; i++)
        {
            if (triangles.Contains(i))
            {
                vertices.Add((marchedCube.GetEdgePoint(i, interpolation) - offsetpos));//Add vertex at correct position
            }
            else
            {
                vertices.Add(Vector3.zero);//We dont need to make this unused vertex compute its position
            }
        }
        triangles.Reverse();//Invert the normals of the faces
        MeshData mesh = new MeshData();
        mesh.vertices = vertices;
        mesh.triangles = triangles;
        return mesh;
    }
>>>>>>> parent of de138c1... Optimized a bit by turning classes into structs
    //Generates all the chunks of the terrain
    public void GenerateChunks() 
    {
        if (chunks == null || chunks.GetLength(0) != worldSize.x || chunks.GetLength(1) != worldSize.y || chunks.GetLength(2) != worldSize.z) chunks = new MarchingCubesChunk[worldSize.x, worldSize.y, worldSize.z];
        chunks[0, 0, 0] = GetComponent<MarchingCubesChunk>();
        for (int x = 0; x < worldSize.x; x++)
        {
            for (int y = 0; y < worldSize.y; y++)
            {
                for (int z = 0; z < worldSize.z; z++)
                {
                    GenerateChunk(x, y, z, true);
                }
            }
        }
    }
    //Generate a single chunk
    public void GenerateChunk(int x, int y, int z, bool recalculateChunks) 
    {
        if (x < 0 || y < 0 || z < 0) return;
        if (x >= chunks.GetLength(0) || y >= chunks.GetLength(1) || z >= chunks.GetLength(2)) return;
        Vector3 chunkPos = TransformCoordinatesChunkToWorld(x, y, z);
        if (chunks[x, y, z] == null)//Generate new chunks if they dont exist yet
        {
            if(densityCalculator.Density(chunkPos) < chunkThreshold) return;//This hcunk is not filled with terrain
            
            GameObject chunk = new GameObject();
            chunk.transform.position = chunkPos;
            chunk.name = x + "-" + y + "-" + z;
<<<<<<< HEAD
            MarchingCubesChunk chunkScript = chunk.GetComponent<MarchingCubesChunk>();
            chunkScript.StartChunk(this, x, y, z);
            //if(densityCalculator.Density(chunkPos) < chunkThreshold) return;//This chunk is not filled with terrain
            //chunkScript.UpdateMesh(MarchCube(chunkPos));

=======
            chunk.transform.parent = transform;
            MarchingCubesChunk chunkScript = chunk.AddComponent<MarchingCubesChunk>();
            chunkScript.StartChunk(this);
            chunkScript.UpdateMesh(MarchCube(chunkPos));
            chunkScript.x = x; chunkScript.y = y; chunkScript.z = z;
>>>>>>> parent of de138c1... Optimized a bit by turning classes into structs
            chunks[x, y, z] = chunkScript;
        }
        else if(recalculateChunks)
        {
            MarchingCubesChunk chunkScript = chunks[x, y, z];
            chunkScript.transform.position = chunkPos;
            chunkScript.UpdateMesh(MarchCube(chunkPos));
        }
    }
    //Generate a single chunk using world coordinates
    public void GenerateChunk(Vector3 pos, bool recalculateChunks)
    {
        Vector3Int chunkCoords = TransformCoordinatesWorldToChunk(pos);
        GenerateChunk(chunkCoords.x, chunkCoords.y, chunkCoords.z, recalculateChunks);
    }
    //Transform chunk coordinates into world coordinates
    public Vector3 TransformCoordinatesChunkToWorld(int x, int y, int z) 
    {
        return new Vector3(x * size * cubeSize, y * size * cubeSize, z * size * cubeSize);
    }
    //Transform chunk coordinates into world coordinates with vector3int
    public Vector3 TransformCoordinatesChunkToWorld(Vector3Int pos)
    {
        return new Vector3(pos.x * size * cubeSize, pos.y * size * cubeSize, pos.z * size * cubeSize);
    }
    public Vector3Int TransformCoordinatesWorldToChunk(Vector3 pos) 
    {
        return new Vector3Int(Mathf.RoundToInt(pos.x / size / cubeSize), Mathf.RoundToInt(pos.y / size / cubeSize), Mathf.RoundToInt(pos.z / size / cubeSize));
    }
    //Set chunk visibility from world coordinates
    public void SetChunkVisibility(Vector3 pos, bool isVisible)
    {
        MarchingCubesChunk chunk = GetChunk(pos);
        if (isVisible) chunk.OnShowChunk();
        else chunk.OnHideChunk();
    }
    //Set chunk visibility
    public void SetChunkVisibility(int x, int y, int z, bool isVisible)
    {
        MarchingCubesChunk chunk = GetChunk(x, y, z);
        if (chunk == null) return;
        if (isVisible) chunk.OnShowChunk();
        else chunk.OnHideChunk();
    }
    //Set chunk visibility with already given chunk
    public void SetChunkVisibility(MarchingCubesChunk chunk, bool isVisible)
    {
        if (chunk == null) return;
        if (isVisible) chunk.OnShowChunk();
        else chunk.OnHideChunk();
    }
    //Set chunk visibilty for all chunks
    public void SetChunksVisibility(bool isVisible) 
    {
        foreach (var chunk in chunks)
        {
            if (chunk == null) continue;
            if (isVisible) chunk.OnShowChunk();
            else chunk.OnHideChunk();
        }
    }
    //Get chunk (Returns null if chunk is outside map bounds)
    public MarchingCubesChunk GetChunk(Vector3 pos) 
    {
        int x, y, z;
        x = Mathf.RoundToInt(pos.x / size / cubeSize);
        y = Mathf.RoundToInt(pos.y / size / cubeSize);
        z = Mathf.RoundToInt(pos.z / size / cubeSize);
        if (x < 0 || y < 0 || z < 0) return null;
        if (x >= chunks.GetLength(0) || y >= chunks.GetLength(1) || z >= chunks.GetLength(2)) return null;
        return chunks[x, y, z];
    }
    //Get chunk (Returns null if chunk is outside map bounds)
    public MarchingCubesChunk GetChunk(int x, int y, int z)
    {
        if (x < 0 || y < 0 || z < 0) return null; 
        if (x >= chunks.GetLength(0) || y >= chunks.GetLength(1) || z >= chunks.GetLength(2)) return null; 
        return chunks[x, y, z];
    }
    //Debug stuff
    private void OnValidate()
    {
        OnValidatePublic();
    }
    public void OnValidatePublic() //Make method so when we change other script's data the mesh also gets updated
    {
        if (onValidate)
        {
<<<<<<< HEAD
            InitMarchingPoints();
            GetComponent<MarchingCubesChunk>().StartChunk(this, 0, 0, 0);
=======
            if(densityCalculator == null) densityCalculator = GetComponent<MarchingCubesDensityScript>();
            GetComponent<MarchingCubesChunk>().StartChunk(this);
>>>>>>> parent of de138c1... Optimized a bit by turning classes into structs
            GetComponent<MarchingCubesChunk>().UpdateMesh(MarchCube(transform.position));
        }
    }
    private void OnDrawGizmos()
    {
        Gizmos.DrawWireCube(((new Vector3(size, size, size)) / 2 * cubeSize), (new Vector3(size, size, size)) * cubeSize);        
    }
}
<<<<<<< HEAD
=======
//Triangulation table from : http://paulbourke.net/geometry/polygonise/
public static class TriangulationTable 
{
    public static int[,] triangulation = new int[256,16]{
    {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 8, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 1, 9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 8, 3, 9, 8, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 2, 10, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 8, 3, 1, 2, 10, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 2, 10, 0, 2, 9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 2, 8, 3, 2, 10, 8, 10, 9, 8, -1, -1, -1, -1, -1, -1, -1 },
    { 3, 11, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 11, 2, 8, 11, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 9, 0, 2, 3, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 11, 2, 1, 9, 11, 9, 8, 11, -1, -1, -1, -1, -1, -1, -1 },
    { 3, 10, 1, 11, 10, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 10, 1, 0, 8, 10, 8, 11, 10, -1, -1, -1, -1, -1, -1, -1 },
    { 3, 9, 0, 3, 11, 9, 11, 10, 9, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 8, 10, 10, 8, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 4, 7, 8, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 4, 3, 0, 7, 3, 4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 1, 9, 8, 4, 7, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 4, 1, 9, 4, 7, 1, 7, 3, 1, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 2, 10, 8, 4, 7, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 3, 4, 7, 3, 0, 4, 1, 2, 10, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 2, 10, 9, 0, 2, 8, 4, 7, -1, -1, -1, -1, -1, -1, -1 },
    { 2, 10, 9, 2, 9, 7, 2, 7, 3, 7, 9, 4, -1, -1, -1, -1 },
    { 8, 4, 7, 3, 11, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 11, 4, 7, 11, 2, 4, 2, 0, 4, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 0, 1, 8, 4, 7, 2, 3, 11, -1, -1, -1, -1, -1, -1, -1 },
    { 4, 7, 11, 9, 4, 11, 9, 11, 2, 9, 2, 1, -1, -1, -1, -1 },
    { 3, 10, 1, 3, 11, 10, 7, 8, 4, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 11, 10, 1, 4, 11, 1, 0, 4, 7, 11, 4, -1, -1, -1, -1 },
    { 4, 7, 8, 9, 0, 11, 9, 11, 10, 11, 0, 3, -1, -1, -1, -1 },
    { 4, 7, 11, 4, 11, 9, 9, 11, 10, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 5, 4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 5, 4, 0, 8, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 5, 4, 1, 5, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 8, 5, 4, 8, 3, 5, 3, 1, 5, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 2, 10, 9, 5, 4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 3, 0, 8, 1, 2, 10, 4, 9, 5, -1, -1, -1, -1, -1, -1, -1 },
    { 5, 2, 10, 5, 4, 2, 4, 0, 2, -1, -1, -1, -1, -1, -1, -1 },
    { 2, 10, 5, 3, 2, 5, 3, 5, 4, 3, 4, 8, -1, -1, -1, -1 },
    { 9, 5, 4, 2, 3, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 11, 2, 0, 8, 11, 4, 9, 5, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 5, 4, 0, 1, 5, 2, 3, 11, -1, -1, -1, -1, -1, -1, -1 },
    { 2, 1, 5, 2, 5, 8, 2, 8, 11, 4, 8, 5, -1, -1, -1, -1 },
    { 10, 3, 11, 10, 1, 3, 9, 5, 4, -1, -1, -1, -1, -1, -1, -1 },
    { 4, 9, 5, 0, 8, 1, 8, 10, 1, 8, 11, 10, -1, -1, -1, -1 },
    { 5, 4, 0, 5, 0, 11, 5, 11, 10, 11, 0, 3, -1, -1, -1, -1 },
    { 5, 4, 8, 5, 8, 10, 10, 8, 11, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 7, 8, 5, 7, 9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 3, 0, 9, 5, 3, 5, 7, 3, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 7, 8, 0, 1, 7, 1, 5, 7, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 5, 3, 3, 5, 7, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 7, 8, 9, 5, 7, 10, 1, 2, -1, -1, -1, -1, -1, -1, -1 },
    { 10, 1, 2, 9, 5, 0, 5, 3, 0, 5, 7, 3, -1, -1, -1, -1 },
    { 8, 0, 2, 8, 2, 5, 8, 5, 7, 10, 5, 2, -1, -1, -1, -1 },
    { 2, 10, 5, 2, 5, 3, 3, 5, 7, -1, -1, -1, -1, -1, -1, -1 },
    { 7, 9, 5, 7, 8, 9, 3, 11, 2, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 5, 7, 9, 7, 2, 9, 2, 0, 2, 7, 11, -1, -1, -1, -1 },
    { 2, 3, 11, 0, 1, 8, 1, 7, 8, 1, 5, 7, -1, -1, -1, -1 },
    { 11, 2, 1, 11, 1, 7, 7, 1, 5, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 5, 8, 8, 5, 7, 10, 1, 3, 10, 3, 11, -1, -1, -1, -1 },
    { 5, 7, 0, 5, 0, 9, 7, 11, 0, 1, 0, 10, 11, 10, 0, -1 },
    { 11, 10, 0, 11, 0, 3, 10, 5, 0, 8, 0, 7, 5, 7, 0, -1 },
    { 11, 10, 5, 7, 11, 5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 10, 6, 5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 8, 3, 5, 10, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 0, 1, 5, 10, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 8, 3, 1, 9, 8, 5, 10, 6, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 6, 5, 2, 6, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 6, 5, 1, 2, 6, 3, 0, 8, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 6, 5, 9, 0, 6, 0, 2, 6, -1, -1, -1, -1, -1, -1, -1 },
    { 5, 9, 8, 5, 8, 2, 5, 2, 6, 3, 2, 8, -1, -1, -1, -1 },
    { 2, 3, 11, 10, 6, 5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 11, 0, 8, 11, 2, 0, 10, 6, 5, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 1, 9, 2, 3, 11, 5, 10, 6, -1, -1, -1, -1, -1, -1, -1 },
    { 5, 10, 6, 1, 9, 2, 9, 11, 2, 9, 8, 11, -1, -1, -1, -1 },
    { 6, 3, 11, 6, 5, 3, 5, 1, 3, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 8, 11, 0, 11, 5, 0, 5, 1, 5, 11, 6, -1, -1, -1, -1 },
    { 3, 11, 6, 0, 3, 6, 0, 6, 5, 0, 5, 9, -1, -1, -1, -1 },
    { 6, 5, 9, 6, 9, 11, 11, 9, 8, -1, -1, -1, -1, -1, -1, -1 },
    { 5, 10, 6, 4, 7, 8, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 4, 3, 0, 4, 7, 3, 6, 5, 10, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 9, 0, 5, 10, 6, 8, 4, 7, -1, -1, -1, -1, -1, -1, -1 },
    { 10, 6, 5, 1, 9, 7, 1, 7, 3, 7, 9, 4, -1, -1, -1, -1 },
    { 6, 1, 2, 6, 5, 1, 4, 7, 8, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 2, 5, 5, 2, 6, 3, 0, 4, 3, 4, 7, -1, -1, -1, -1 },
    { 8, 4, 7, 9, 0, 5, 0, 6, 5, 0, 2, 6, -1, -1, -1, -1 },
    { 7, 3, 9, 7, 9, 4, 3, 2, 9, 5, 9, 6, 2, 6, 9, -1 },
    { 3, 11, 2, 7, 8, 4, 10, 6, 5, -1, -1, -1, -1, -1, -1, -1 },
    { 5, 10, 6, 4, 7, 2, 4, 2, 0, 2, 7, 11, -1, -1, -1, -1 },
    { 0, 1, 9, 4, 7, 8, 2, 3, 11, 5, 10, 6, -1, -1, -1, -1 },
    { 9, 2, 1, 9, 11, 2, 9, 4, 11, 7, 11, 4, 5, 10, 6, -1 },
    { 8, 4, 7, 3, 11, 5, 3, 5, 1, 5, 11, 6, -1, -1, -1, -1 },
    { 5, 1, 11, 5, 11, 6, 1, 0, 11, 7, 11, 4, 0, 4, 11, -1 },
    { 0, 5, 9, 0, 6, 5, 0, 3, 6, 11, 6, 3, 8, 4, 7, -1 },
    { 6, 5, 9, 6, 9, 11, 4, 7, 9, 7, 11, 9, -1, -1, -1, -1 },
    { 10, 4, 9, 6, 4, 10, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 4, 10, 6, 4, 9, 10, 0, 8, 3, -1, -1, -1, -1, -1, -1, -1 },
    { 10, 0, 1, 10, 6, 0, 6, 4, 0, -1, -1, -1, -1, -1, -1, -1 },
    { 8, 3, 1, 8, 1, 6, 8, 6, 4, 6, 1, 10, -1, -1, -1, -1 },
    { 1, 4, 9, 1, 2, 4, 2, 6, 4, -1, -1, -1, -1, -1, -1, -1 },
    { 3, 0, 8, 1, 2, 9, 2, 4, 9, 2, 6, 4, -1, -1, -1, -1 },
    { 0, 2, 4, 4, 2, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 8, 3, 2, 8, 2, 4, 4, 2, 6, -1, -1, -1, -1, -1, -1, -1 },
    { 10, 4, 9, 10, 6, 4, 11, 2, 3, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 8, 2, 2, 8, 11, 4, 9, 10, 4, 10, 6, -1, -1, -1, -1 },
    { 3, 11, 2, 0, 1, 6, 0, 6, 4, 6, 1, 10, -1, -1, -1, -1 },
    { 6, 4, 1, 6, 1, 10, 4, 8, 1, 2, 1, 11, 8, 11, 1, -1 },
    { 9, 6, 4, 9, 3, 6, 9, 1, 3, 11, 6, 3, -1, -1, -1, -1 },
    { 8, 11, 1, 8, 1, 0, 11, 6, 1, 9, 1, 4, 6, 4, 1, -1 },
    { 3, 11, 6, 3, 6, 0, 0, 6, 4, -1, -1, -1, -1, -1, -1, -1 },
    { 6, 4, 8, 11, 6, 8, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 7, 10, 6, 7, 8, 10, 8, 9, 10, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 7, 3, 0, 10, 7, 0, 9, 10, 6, 7, 10, -1, -1, -1, -1 },
    { 10, 6, 7, 1, 10, 7, 1, 7, 8, 1, 8, 0, -1, -1, -1, -1 },
    { 10, 6, 7, 10, 7, 1, 1, 7, 3, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 2, 6, 1, 6, 8, 1, 8, 9, 8, 6, 7, -1, -1, -1, -1 },
    { 2, 6, 9, 2, 9, 1, 6, 7, 9, 0, 9, 3, 7, 3, 9, -1 },
    { 7, 8, 0, 7, 0, 6, 6, 0, 2, -1, -1, -1, -1, -1, -1, -1 },
    { 7, 3, 2, 6, 7, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 2, 3, 11, 10, 6, 8, 10, 8, 9, 8, 6, 7, -1, -1, -1, -1 },
    { 2, 0, 7, 2, 7, 11, 0, 9, 7, 6, 7, 10, 9, 10, 7, -1 },
    { 1, 8, 0, 1, 7, 8, 1, 10, 7, 6, 7, 10, 2, 3, 11, -1 },
    { 11, 2, 1, 11, 1, 7, 10, 6, 1, 6, 7, 1, -1, -1, -1, -1 },
    { 8, 9, 6, 8, 6, 7, 9, 1, 6, 11, 6, 3, 1, 3, 6, -1 },
    { 0, 9, 1, 11, 6, 7, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 7, 8, 0, 7, 0, 6, 3, 11, 0, 11, 6, 0, -1, -1, -1, -1 },
    { 7, 11, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 7, 6, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 3, 0, 8, 11, 7, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 1, 9, 11, 7, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 8, 1, 9, 8, 3, 1, 11, 7, 6, -1, -1, -1, -1, -1, -1, -1 },
    { 10, 1, 2, 6, 11, 7, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 2, 10, 3, 0, 8, 6, 11, 7, -1, -1, -1, -1, -1, -1, -1 },
    { 2, 9, 0, 2, 10, 9, 6, 11, 7, -1, -1, -1, -1, -1, -1, -1 },
    { 6, 11, 7, 2, 10, 3, 10, 8, 3, 10, 9, 8, -1, -1, -1, -1 },
    { 7, 2, 3, 6, 2, 7, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 7, 0, 8, 7, 6, 0, 6, 2, 0, -1, -1, -1, -1, -1, -1, -1 },
    { 2, 7, 6, 2, 3, 7, 0, 1, 9, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 6, 2, 1, 8, 6, 1, 9, 8, 8, 7, 6, -1, -1, -1, -1 },
    { 10, 7, 6, 10, 1, 7, 1, 3, 7, -1, -1, -1, -1, -1, -1, -1 },
    { 10, 7, 6, 1, 7, 10, 1, 8, 7, 1, 0, 8, -1, -1, -1, -1 },
    { 0, 3, 7, 0, 7, 10, 0, 10, 9, 6, 10, 7, -1, -1, -1, -1 },
    { 7, 6, 10, 7, 10, 8, 8, 10, 9, -1, -1, -1, -1, -1, -1, -1 },
    { 6, 8, 4, 11, 8, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 3, 6, 11, 3, 0, 6, 0, 4, 6, -1, -1, -1, -1, -1, -1, -1 },
    { 8, 6, 11, 8, 4, 6, 9, 0, 1, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 4, 6, 9, 6, 3, 9, 3, 1, 11, 3, 6, -1, -1, -1, -1 },
    { 6, 8, 4, 6, 11, 8, 2, 10, 1, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 2, 10, 3, 0, 11, 0, 6, 11, 0, 4, 6, -1, -1, -1, -1 },
    { 4, 11, 8, 4, 6, 11, 0, 2, 9, 2, 10, 9, -1, -1, -1, -1 },
    { 10, 9, 3, 10, 3, 2, 9, 4, 3, 11, 3, 6, 4, 6, 3, -1 },
    { 8, 2, 3, 8, 4, 2, 4, 6, 2, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 4, 2, 4, 6, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 9, 0, 2, 3, 4, 2, 4, 6, 4, 3, 8, -1, -1, -1, -1 },
    { 1, 9, 4, 1, 4, 2, 2, 4, 6, -1, -1, -1, -1, -1, -1, -1 },
    { 8, 1, 3, 8, 6, 1, 8, 4, 6, 6, 10, 1, -1, -1, -1, -1 },
    { 10, 1, 0, 10, 0, 6, 6, 0, 4, -1, -1, -1, -1, -1, -1, -1 },
    { 4, 6, 3, 4, 3, 8, 6, 10, 3, 0, 3, 9, 10, 9, 3, -1 },
    { 10, 9, 4, 6, 10, 4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 4, 9, 5, 7, 6, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 8, 3, 4, 9, 5, 11, 7, 6, -1, -1, -1, -1, -1, -1, -1 },
    { 5, 0, 1, 5, 4, 0, 7, 6, 11, -1, -1, -1, -1, -1, -1, -1 },
    { 11, 7, 6, 8, 3, 4, 3, 5, 4, 3, 1, 5, -1, -1, -1, -1 },
    { 9, 5, 4, 10, 1, 2, 7, 6, 11, -1, -1, -1, -1, -1, -1, -1 },
    { 6, 11, 7, 1, 2, 10, 0, 8, 3, 4, 9, 5, -1, -1, -1, -1 },
    { 7, 6, 11, 5, 4, 10, 4, 2, 10, 4, 0, 2, -1, -1, -1, -1 },
    { 3, 4, 8, 3, 5, 4, 3, 2, 5, 10, 5, 2, 11, 7, 6, -1 },
    { 7, 2, 3, 7, 6, 2, 5, 4, 9, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 5, 4, 0, 8, 6, 0, 6, 2, 6, 8, 7, -1, -1, -1, -1 },
    { 3, 6, 2, 3, 7, 6, 1, 5, 0, 5, 4, 0, -1, -1, -1, -1 },
    { 6, 2, 8, 6, 8, 7, 2, 1, 8, 4, 8, 5, 1, 5, 8, -1 },
    { 9, 5, 4, 10, 1, 6, 1, 7, 6, 1, 3, 7, -1, -1, -1, -1 },
    { 1, 6, 10, 1, 7, 6, 1, 0, 7, 8, 7, 0, 9, 5, 4, -1 },
    { 4, 0, 10, 4, 10, 5, 0, 3, 10, 6, 10, 7, 3, 7, 10, -1 },
    { 7, 6, 10, 7, 10, 8, 5, 4, 10, 4, 8, 10, -1, -1, -1, -1 },
    { 6, 9, 5, 6, 11, 9, 11, 8, 9, -1, -1, -1, -1, -1, -1, -1 },
    { 3, 6, 11, 0, 6, 3, 0, 5, 6, 0, 9, 5, -1, -1, -1, -1 },
    { 0, 11, 8, 0, 5, 11, 0, 1, 5, 5, 6, 11, -1, -1, -1, -1 },
    { 6, 11, 3, 6, 3, 5, 5, 3, 1, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 2, 10, 9, 5, 11, 9, 11, 8, 11, 5, 6, -1, -1, -1, -1 },
    { 0, 11, 3, 0, 6, 11, 0, 9, 6, 5, 6, 9, 1, 2, 10, -1 },
    { 11, 8, 5, 11, 5, 6, 8, 0, 5, 10, 5, 2, 0, 2, 5, -1 },
    { 6, 11, 3, 6, 3, 5, 2, 10, 3, 10, 5, 3, -1, -1, -1, -1 },
    { 5, 8, 9, 5, 2, 8, 5, 6, 2, 3, 8, 2, -1, -1, -1, -1 },
    { 9, 5, 6, 9, 6, 0, 0, 6, 2, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 5, 8, 1, 8, 0, 5, 6, 8, 3, 8, 2, 6, 2, 8, -1 },
    { 1, 5, 6, 2, 1, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 3, 6, 1, 6, 10, 3, 8, 6, 5, 6, 9, 8, 9, 6, -1 },
    { 10, 1, 0, 10, 0, 6, 9, 5, 0, 5, 6, 0, -1, -1, -1, -1 },
    { 0, 3, 8, 5, 6, 10, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 10, 5, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 11, 5, 10, 7, 5, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 11, 5, 10, 11, 7, 5, 8, 3, 0, -1, -1, -1, -1, -1, -1, -1 },
    { 5, 11, 7, 5, 10, 11, 1, 9, 0, -1, -1, -1, -1, -1, -1, -1 },
    { 10, 7, 5, 10, 11, 7, 9, 8, 1, 8, 3, 1, -1, -1, -1, -1 },
    { 11, 1, 2, 11, 7, 1, 7, 5, 1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 8, 3, 1, 2, 7, 1, 7, 5, 7, 2, 11, -1, -1, -1, -1 },
    { 9, 7, 5, 9, 2, 7, 9, 0, 2, 2, 11, 7, -1, -1, -1, -1 },
    { 7, 5, 2, 7, 2, 11, 5, 9, 2, 3, 2, 8, 9, 8, 2, -1 },
    { 2, 5, 10, 2, 3, 5, 3, 7, 5, -1, -1, -1, -1, -1, -1, -1 },
    { 8, 2, 0, 8, 5, 2, 8, 7, 5, 10, 2, 5, -1, -1, -1, -1 },
    { 9, 0, 1, 5, 10, 3, 5, 3, 7, 3, 10, 2, -1, -1, -1, -1 },
    { 9, 8, 2, 9, 2, 1, 8, 7, 2, 10, 2, 5, 7, 5, 2, -1 },
    { 1, 3, 5, 3, 7, 5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 8, 7, 0, 7, 1, 1, 7, 5, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 0, 3, 9, 3, 5, 5, 3, 7, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 8, 7, 5, 9, 7, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 5, 8, 4, 5, 10, 8, 10, 11, 8, -1, -1, -1, -1, -1, -1, -1 },
    { 5, 0, 4, 5, 11, 0, 5, 10, 11, 11, 3, 0, -1, -1, -1, -1 },
    { 0, 1, 9, 8, 4, 10, 8, 10, 11, 10, 4, 5, -1, -1, -1, -1 },
    { 10, 11, 4, 10, 4, 5, 11, 3, 4, 9, 4, 1, 3, 1, 4, -1 },
    { 2, 5, 1, 2, 8, 5, 2, 11, 8, 4, 5, 8, -1, -1, -1, -1 },
    { 0, 4, 11, 0, 11, 3, 4, 5, 11, 2, 11, 1, 5, 1, 11, -1 },
    { 0, 2, 5, 0, 5, 9, 2, 11, 5, 4, 5, 8, 11, 8, 5, -1 },
    { 9, 4, 5, 2, 11, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 2, 5, 10, 3, 5, 2, 3, 4, 5, 3, 8, 4, -1, -1, -1, -1 },
    { 5, 10, 2, 5, 2, 4, 4, 2, 0, -1, -1, -1, -1, -1, -1, -1 },
    { 3, 10, 2, 3, 5, 10, 3, 8, 5, 4, 5, 8, 0, 1, 9, -1 },
    { 5, 10, 2, 5, 2, 4, 1, 9, 2, 9, 4, 2, -1, -1, -1, -1 },
    { 8, 4, 5, 8, 5, 3, 3, 5, 1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 4, 5, 1, 0, 5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 8, 4, 5, 8, 5, 3, 9, 0, 5, 0, 3, 5, -1, -1, -1, -1 },
    { 9, 4, 5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 4, 11, 7, 4, 9, 11, 9, 10, 11, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 8, 3, 4, 9, 7, 9, 11, 7, 9, 10, 11, -1, -1, -1, -1 },
    { 1, 10, 11, 1, 11, 4, 1, 4, 0, 7, 4, 11, -1, -1, -1, -1 },
    { 3, 1, 4, 3, 4, 8, 1, 10, 4, 7, 4, 11, 10, 11, 4, -1 },
    { 4, 11, 7, 9, 11, 4, 9, 2, 11, 9, 1, 2, -1, -1, -1, -1 },
    { 9, 7, 4, 9, 11, 7, 9, 1, 11, 2, 11, 1, 0, 8, 3, -1 },
    { 11, 7, 4, 11, 4, 2, 2, 4, 0, -1, -1, -1, -1, -1, -1, -1 },
    { 11, 7, 4, 11, 4, 2, 8, 3, 4, 3, 2, 4, -1, -1, -1, -1 },
    { 2, 9, 10, 2, 7, 9, 2, 3, 7, 7, 4, 9, -1, -1, -1, -1 },
    { 9, 10, 7, 9, 7, 4, 10, 2, 7, 8, 7, 0, 2, 0, 7, -1 },
    { 3, 7, 10, 3, 10, 2, 7, 4, 10, 1, 10, 0, 4, 0, 10, -1 },
    { 1, 10, 2, 8, 7, 4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 4, 9, 1, 4, 1, 7, 7, 1, 3, -1, -1, -1, -1, -1, -1, -1 },
    { 4, 9, 1, 4, 1, 7, 0, 8, 1, 8, 7, 1, -1, -1, -1, -1 },
    { 4, 0, 3, 7, 4, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 4, 8, 7, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 10, 8, 10, 11, 8, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 3, 0, 9, 3, 9, 11, 11, 9, 10, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 1, 10, 0, 10, 8, 8, 10, 11, -1, -1, -1, -1, -1, -1, -1 },
    { 3, 1, 10, 11, 3, 10, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 2, 11, 1, 11, 9, 9, 11, 8, -1, -1, -1, -1, -1, -1, -1 },
    { 3, 0, 9, 3, 9, 11, 1, 2, 9, 2, 11, 9, -1, -1, -1, -1 },
    { 0, 2, 11, 8, 0, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 3, 2, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 2, 3, 8, 2, 8, 10, 10, 8, 9, -1, -1, -1, -1, -1, -1, -1 },
    { 9, 10, 2, 0, 9, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 2, 3, 8, 2, 8, 10, 0, 1, 8, 1, 10, 8, -1, -1, -1, -1 },
    { 1, 10, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 1, 3, 8, 9, 1, 8, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 9, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    { 0, 3, 8, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 },
    {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 }
    };
}
//The cube that we are going to march
public class MarchedCube
{
    private float cubeSize;
    private float threshold;//If density is higher than this, there is terrain at that point
    public int outcase;
    MarchingCubesDensityScript densityCalculator;
    //Instantiate new MarchedCube class
    public MarchedCube(float _cubeSize, float _threshold, MarchingCubesDensityScript _densityCalculator) //Initialization of the MarchedCube
    {
        //Setup parameters
        cubeSize = _cubeSize;
        threshold = _threshold;
        densityCalculator = _densityCalculator;

        corners = new MarchedCubeCorner[8];
        for (int i = 0; i < 8; i++)
        {
            corners[i] = new MarchedCubeCorner();
        }
        edges = new MarchedCubeEdge[12];
        for (int i = 0; i < 12; i++)
        {
            edges[i] = new MarchedCubeEdge();
        }
        //Set correct corner points for edges
        edges[0].vertex0 = corners[0]; edges[0].vertex1 = corners[1];
        edges[1].vertex0 = corners[1]; edges[1].vertex1 = corners[2];
        edges[2].vertex0 = corners[2]; edges[2].vertex1 = corners[3];
        edges[3].vertex0 = corners[3]; edges[3].vertex1 = corners[0];
        edges[4].vertex0 = corners[4]; edges[4].vertex1 = corners[5];
        edges[5].vertex0 = corners[5]; edges[5].vertex1 = corners[6];
        edges[6].vertex0 = corners[6]; edges[6].vertex1 = corners[7];
        edges[7].vertex0 = corners[7]; edges[7].vertex1 = corners[4];
        edges[8].vertex0 = corners[0]; edges[8].vertex1 = corners[4];
        edges[9].vertex0 = corners[1]; edges[9].vertex1 = corners[5];
        edges[10].vertex0 = corners[2]; edges[10].vertex1 = corners[6];
        edges[11].vertex0 = corners[3]; edges[11].vertex1 = corners[7];
    }
    //Set parameters for an already generated MarchedCube class
    public void SetParams(float _cubeSize, float _threshold, MarchingCubesDensityScript _densityCalculator) 
    {
        cubeSize = _cubeSize;
        threshold = _threshold;
        densityCalculator = _densityCalculator;
    }
    public MarchedCubeCorner[] corners = new MarchedCubeCorner[8];
    public MarchedCubeEdge[] edges = new MarchedCubeEdge[12];
    public Vector3 GetEdgePoint(int edgeIndex, bool smoothed) 
    {
        //return edgePoints[edgeIndex];
        MarchedCubeCorner corner0 = edges[edgeIndex].vertex0;
        MarchedCubeCorner corner1 = edges[edgeIndex].vertex1;
        float density0 = corner0.density;
        float density1 = corner1.density;

        //float estimatedSurface = (threshold - density0) / (density1 - density0);  
        float estimatedSurface = Mathf.InverseLerp(density0, density1, threshold);
        if(smoothed) 
            return Vector3.Slerp(corner0.pos, corner1.pos, estimatedSurface);
        else
            return Vector3.Lerp(corner0.pos, corner1.pos, 0.5f);        
    }

    public int MarchCube(Vector3 newpos) 
    {
        outcase = 0;
        //Set corners new position
        corners[0].pos = newpos;
        corners[1].pos = newpos + (new Vector3(0, 1, 0) * cubeSize);
        corners[2].pos = newpos + (new Vector3(1, 1, 0) * cubeSize);
        corners[3].pos = newpos + (new Vector3(1, 0, 0) * cubeSize);
        corners[4].pos = newpos + (new Vector3(0, 0, 1) * cubeSize);
        corners[5].pos = newpos + (new Vector3(0, 1, 1) * cubeSize);
        corners[6].pos = newpos + (new Vector3(1, 1, 1) * cubeSize);
        corners[7].pos = newpos + (new Vector3(1, 0, 1) * cubeSize);       

        for (int i = 0; i < corners.Length; i++)
        {
            corners[i].density = Density(corners[i].pos);
            corners[i].bit = corners[i].density < threshold;
            outcase += (corners[i].bit ? 1 : 0) * Mathf.RoundToInt(Mathf.Pow(2, i));
        } 

        return outcase;
    }
    //How much terrain density at a current 3d point
    private float Density(Vector3 pos)
    {
        return densityCalculator.Density(pos);
    }
}
//Each 8 Corners of the cube
public class MarchedCubeCorner
{
    public bool bit;
    public float density;
    public Vector3 pos;
}
//Each 12 Edges of the cube
public class MarchedCubeEdge 
{
    public Vector3 position;
    public MarchedCubeCorner vertex0;
    public MarchedCubeCorner vertex1;
}
>>>>>>> parent of de138c1... Optimized a bit by turning classes into structs
